pull_request_rules:
  - name: merge on label
    conditions:
      - label=queue
      - base=main
    actions:
      queue:
        name: default

queue_rules:
  - name: default
    conditions:
      - label=merge
