pull_request_rules:
  - name: Merge on approvalllllll
    conditions:
      - label=Approved
      - base=main
    actions:
      queue:
        name: default

queue_rules:
  - name: default
    conditions:
      - base=main
