pull_request_rules:
  - name: Merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
    actions:
      queue:
        name: default

queue_rules:
  - name: default
    conditions:
      - base=main
